### ISSUE TITLE
Additional row annotations

### ISSUE THREAD

**Issue by ywzhang071394** [junjunlab/ClusterGVis#103]
Hi,

Thank you for the nice tool. We recently used it to plot our expression data but found that some additional row annotations cannot be easily added. I am not sure if we missed any paramters or ClusterGVis have never supported this function. I would appreaciate if you can give a brief explanation.

Thanks!

**Comment by junjunlab** [comment]
Please supply your code and results.

**Comment by junjunlab** [comment]
What are your gene types and variants？ Show me a example diagram？

**Comment by ywzhang071394** [comment]
Here is an example from pheatmap, which has row annotations "GeneType", "Location" and "SVtype".
I am just wondering if clustergvis has similar functions to customize row annotations.
![image](https://github.com/user-attachments/assets/af27d1ce-b12e-48b5-96f0-ed2c7290a778)
