### ISSUE TITLE
同时添加boxplot和line的时候，会有部分box被覆盖

### ISSUE THREAD

**Issue by kangkc16** [junjunlab/ClusterGVis#108]
作者你好，我通过修改xscale的方式完整了展示所有的box，但是line的起始和终止位置并没有改变，我应该怎么样调整数据改动line呢？
![image](https://github.com/user-attachments/assets/56533bfa-669f-4d08-aede-c90e835a3f42)

**Comment by junjunlab** [comment]
用pdf函数保存再打开试试

**Comment by kangkc16** [comment]
> 用pdf函数保存再打开试试

我保存了以后还是这个样子，line的起始和终止位置贴在两段。
我现在怀疑是xscale的修改只覆盖到了boxplot，但您这边是用grid::grid.lines()进行的绘图，我对方式并不熟悉。

**Comment by junjunlab** [comment]
你可以把代码发我测试看看

**Comment by kangkc16** [comment]
> 你可以把代码发我测试看看

我修改了visCluster.R的639-643行。
`if(add.box == TRUE & add.line != TRUE){
          xscale = c(-0.1,1.1)
        }else{
          xscale = c(-0.1,1.1)
        }`

**Comment by junjunlab** [comment]
重新安装一下吧，代码我更新了：

```
library(ClusterGVis)
# add boxplot
pdf('testbx.pdf',height = 10,width = 6)
visCluster(object = ck,
           plot.type = "both",
           column_names_rot = 45,
           add.box = T)
dev.off()
```
![1732197602917](https://github.com/user-attachments/assets/b0d45116-a3a8-4c81-945a-77d1f3a5b462)

**Comment by kangkc16** [comment]
非常感谢！
