### ISSUE TITLE
Add multigroup column annotation?

### ISSUE THREAD

**Issue by timedreamer** [junjunlab/ClusterGVis#15]
Hi there,

Bravo for the package! One question/suggestion: is there any way to add multiple-column annotations? 

I'm aware of the `sample.group` parameter, but that can only allow one grouping (which is most of the case). I want to add extra column annotations, but got the error below.

```
Error in ComplexHeatmap::Heatmap(as.matrix(mat), name = "Z-score", cluster_columns = FALSE,  : 
  formal argument "top_annotation" matched by multiple actual arguments
```

Any idea how I can add extra column annotations? Something like this:

```
ha = HeatmapAnnotation(foo1 = rep(c("D1","D2"), each = 4),
                       foo2 = rep(c("E1", "E1", "E2", "E2"), 2))
draw(ha)
```

Thanks!
Ji

**Comment by junjunlab** [comment]
see [ClusterGVis 添加多个样本注释](https://mp.weixin.qq.com/s?__biz=MzkyMTI1MTYxNA==&mid=2247507410&idx=1&sn=c33809620a13392f420a9bc1160400ac&chksm=c184e7a3f6f36eb5286ca59cba9cc0f81bb2e1d8e6f769588faf5f324c945b8cfe8f50708780#rd).

**Comment by timedreamer** [comment]
Thanks for implementing `HeatmapAnnotation`!
