### ISSUE TITLE
GO+KEGG注释有问题

### ISSUE THREAD

**Issue by lihaicheng7003** [junjunlab/ClusterGVis#23]
GO和KEGG在图中，如果注释短，就会合成一行
![image](https://user-images.githubusercontent.com/61043072/225644015-d2eb64b1-61f6-432f-a018-2f29548eb0a7.png)

**Comment by junjunlab** [comment]
设置word_wrap和add_new_line应该可以调整

**Comment by lihaicheng7003** [comment]
今天试了一下代码，只需要`add_new_line = T`，控制文本换行方式就可以了，大佬下次可以把微信文章中代码修改一下修改一下
https://mp.weixin.qq.com/s?__biz=MzkyMTI1MTYxNA==&mid=2247508362&idx=1&sn=68c90f6b6cf328f220c2926e1ff68df6&chksm=c1849bfbf6f312eddc8839706dc81984fb6da270dec3505b351b69f775e49e92ea585b3c5d1c&token=1432898004&lang=zh_CN#rd
