### ISSUE TITLE
prepareDataFromscRNA 报错

### ISSUE THREAD

**Issue by Andymare1994** [junjunlab/ClusterGVis#54]
pbmc<-scObject
> new.cluster.ids <- c("Endothelial","Pericytes","Fibroblast","T and NK cells", "Mast cells","DCs","Macrophage","Granulocytes","B cells" )
> names(new.cluster.ids) <- levels(pbmc)
> pbmc <- RenameIdents(pbmc, new.cluster.ids)
> levels(pbmc)
[1] "Endothelial"    "Pericytes"      "Fibroblast"     "T and NK cells" "Mast cells"     "DCs"            "Macrophage"     "Granulocytes"   "B cells"       
> pbmc.markers <- pbmc.markers.all %>%
+   dplyr::group_by(cluster) %>%
+   dplyr::top_n(n = 20, wt = avg_log2FC)
> head(pbmc.markers)
# A tibble: 6 × 7
# Groups:   cluster [1]
  p_val avg_log2FC pct.1 pct.2 p_val_adj cluster    gene  
  <dbl>      <dbl> <dbl> <dbl>     <dbl> <fct>      <chr> 
1     0       3.79 0.74  0.035         0 Fibroblast CCL14 
2     0       3.48 0.679 0.031         0 Fibroblast ACKR1 
3     0       3.38 0.922 0.164         0 Fibroblast TM4SF1
4     0       3.24 0.962 0.039         0 Fibroblast ADGRL4
5     0       3.19 0.982 0.225         0 Fibroblast PECAM1
6     0       3.15 0.918 0.038         0 Fibroblast VWF   
> st.data <- prepareDataFromscRNA(object = pbmc,
+                                 diffData = pbmc.markers,
+                                 showAverage = TRUE)
Error in dimnames(x) <- dn : 
  length of 'dimnames' [2] not equal to array extent
请问大佬，做到这一步总是报错怎么办

**Comment by suyy1** [comment]
我也想知道555

**Comment by CHUNYINCHO** [comment]
你后面是如何解决的？

**Comment by suyy1** [comment]
您好，您的邮件苏映悦已收到，谢谢~

**Comment by suyy1** [comment]
您好，您的邮件苏映悦已收到，谢谢~
