### ISSUE TITLE
How to remove the gene size componten in the line box?

### ISSUE THREAD

**Issue by SunShiFu86** [junjunlab/ClusterGVis#62]
Hi Jun,

Thanks for developing this great package. 
My question is how to remove the gene size componten in the line box, because sometimes it blocks the line.

![2024-01-23 11-48-45屏幕截图](https://github.com/junjunlab/ClusterGVis/assets/137992148/707425f4-13af-4569-a5e9-6221c5437191)

Cheers,

**Comment by junjunlab** [comment]
You can use **textbox.pos** and **textbox.size** change the position and text size. But you can not remove it.

**Comment by SunShiFu86** [comment]
> You can use **textbox.pos** and **textbox.size** change the position and text size. But you can not remove it.

Thanks
