### ISSUE TITLE
非常感谢！

### ISSUE THREAD

**Issue by SongXiaoYi** [junjunlab/ClusterGVis#8]
谢谢大神做的新包，一直都是您的粉丝。
我在用您的包跑示例数据的时候出现了如下错误：
Error in ComplexHeatmap::anno_block(align_to = align_to, panel_fun = function(index,  : 
  unused arguments (align_to = align_to, panel_fun = function(index, nm) {
    npos = as.numeric(unlist(strsplit(nm, split = "C"))[2])
    grid::grid.rect(gp = grid::gpar(fill = colanno[npos], col = NA))
    if (annnoblock.text == TRUE) {
        grid::grid.text(label = paste("n:", length(index), sep = ""), rot = 90, gp = grid::gpar(col = annnoblock.gp[1], fontsize = as.numeric(annnoblock.gp[2])))
    }
})

考虑应该是您在修改本库的代码。

其实您可以在这个库里新开一个专用于修整开发的branch, 这样可能就会避免别人在您修改代码的时候下载到使用会出错的包，待您在
这个branch上修改测试完成后您可以把您修改的内容并入main的这个主要的branch, 这样可以不耽误使用，谢谢大神

**Comment by junjunlab** [comment]
感谢建议,报错你更新到最新的complexheatmap就行了。

**Comment by SongXiaoYi** [comment]
好的，谢谢大神
