### ISSUE TITLE
不对scRNA数据求平均值，visCluster绘制热图时，无法控制列名旋转度

### ISSUE THREAD

**Issue by Leilingshan** [junjunlab/ClusterGVis#81]
作者您好，
       如标题所示，为什么在对scRNA的基因表达不求平均值时，visCluster的参数“column_names_rot”无法调节列名（分群或分组名）的旋转度呢？此时，列名（分群或分组名）总是水平显示。
       请问如何才能正确调整旋转度呢？
谢谢！

**Comment by junjunlab** [comment]
请使用 **column_title_rot** 进行调整。

**Comment by Leilingshan** [comment]
> 请使用 **column_title_rot** 进行调整。

问题已解决，非常感谢！
